jobs:
  publish-canary-docker:
    if: github.repository == 'microsoft/playwright-java'
    name: publish to DockerHub
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: azure/docker-login@v1
      with:
        login-server: playwright.azurecr.io
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: playwright
    - continue-on-error: true
      name: Set up Docker QEMU for arm64 docker builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: (github.event_name != 'workflow_dispatch' && !github.event.release.prerelease)
        || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_release
        == 'true')
      run: ./utils/docker/publish_docker.sh stable
    - continue-on-error: true
      if: (github.event_name != 'workflow_dispatch' && github.event.release.prerelease)
        || (github.event_name == 'workflow_dispatch' && github.event.inputs.is_release
        != 'true')
      run: ./utils/docker/publish_docker.sh canary
name: Publish Release Docker
on:
  repository_dispatch:
    types: trigger-ga___publish_docker.yml
