jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build Docker image
      run: bash utils/docker/build.sh --amd64 ${{ matrix.flavor }} playwright-java:localbuild-${{
        matrix.flavor }}
    - continue-on-error: true
      name: Test
      run: 'CONTAINER_ID="$(docker run --rm --ipc=host -v $(pwd):/root/playwright
        --name playwright-docker-test -d -t playwright-java:localbuild-${{ matrix.flavor
        }} /bin/bash)"

        docker exec "${CONTAINER_ID}" /root/playwright/tools/test-local-installation/create_project_and_run_tests.sh

        '
    strategy:
      fail-fast: false
      matrix:
        flavor:
        - focal
        - jammy
    timeout-minutes: 120
name: Docker
on:
  repository_dispatch:
    types: trigger-ga___test_docker.yml
