jobs:
  verify:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: microsoft/playwright-github-action@v1
    - continue-on-error: true
      name: Download drivers
      run: scripts/download_driver_for_all_platforms.sh
    - continue-on-error: true
      name: Regenerate APIs
      run: scripts/generate_api.sh
    - continue-on-error: true
      name: Update browser versions in README
      run: scripts/update_readme.sh
    - continue-on-error: true
      name: Verify API is up to date
      run: "if [[ -n $(git status -s) ]]; then\n  echo \"ERROR: generated interfaces/docs\
        \ differ from the current sources:\"\n  git diff\n  exit 1\nfi\n"
    timeout-minutes: 30
name: Verify API
on:
  repository_dispatch:
    types: trigger-ga___verify_api.yml
